name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet pack -p:PackAsTool=true -p:ReadyToRun=false -p:PublishTrimmed=false -c release -o dist Breach/Breach.csproj
      - name: Nuget Push
        env:
          token: ${{ secrets.nuget_token }}
        run: dotnet nuget push dist/breach*.nupkg --api-key "$token" --source https://api.nuget.org/v3/index.json